version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgresql/conf:/etc/postgresql/
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
      
  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080
volumes:
  postgres:
